name: Sync to klashxx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código de la Organización
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false # <--- ¡ESTO ES LO QUE ARREGLA EL ERROR!

      - name: Sincronizar con klashxx/afp-core
        run: |
          git config --global user.name "klashxx"
          git config --global user.email "klashxx@gmail.com"
          
          # Usamos tu usuario y el token directamente en la URL
          git remote add target https://klashxx:${{ secrets.PERSONAL_TOKEN }}@github.com/klashxx/afp-core.git
          
          # Empujar
          git push target main --force
