name: Sync to klashxx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código de la Organización
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Descarga todo el historial para poder hacer push force correctamente

      - name: Sincronizar con klashxx/afp-core
        run: |
          # 1. Configurar identidad de Git
          git config --global user.name "klashxx"
          git config --global user.email "klashxx@gmail.com"
          
          # 2. Añadir el repositorio destino como remoto
          # Usamos el token guardado en los secretos de la organización
          git remote add target https://oauth2:${{ secrets.PERSONAL_TOKEN }}@github.com/klashxx/afp-core.git
          
          # 3. Empujar los cambios (Modo Espejo)
          # El flag --force asegura que tu repo quede idéntico al de la org.
          # Si NO quieres sobrescribir tu historial, quita el '--force', 
          # pero podría fallar si tienes cambios locales.
          git push target main --force
